apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vehicles-redis-permit-access
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: {{ .GATE_POD_NAME }}
    ports:
    - port: 6379
      protocol: TCP
  podSelector:
    matchLabels:
      name: {{ .NAME }}
