apiVersion: v1
kind: Service
metadata:
  labels:
    name: vehicles-redis
    service: vehicles-redis
    project: leds-person
  name: {{ .NAME }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: {{ .NAME }}
