---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .NAME }}
  labels:
    cert-manager.io/solver: route53
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/whitelist-source-range: | 
      62.25.109.196/32,
      52.48.127.144/28,
      52.209.62.128/25,
      52.56.62.128/25,
      52.56.221.216/32,
      18.130.11.142/32,
      18.130.6.5/32,
      195.171.80.153/32,
      90.216.22.63/32,
      195.166.151.52/32,
      52.56.62.210/32

    kubernetes.io/ingress.class: nginx-external
    ingress.kubernetes.io/proxy-body-size: 100m
spec:
  tls:
    - hosts:
        - {{ .EXTERNAL_URL }}
      secretName: {{ .NAME }}-tls-cmio
  rules:
    - host: {{ .EXTERNAL_URL }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .NAME }}
              servicePort: 80
...
