---
apiVersion: v1
kind: Service
metadata:
  name: {{ .NAME }}
  labels:
    project: leds-vehicles
spec:
  selector:
    app: {{ .NAME }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .PORT }}
      targetPort: 3000
...
